[package]
name = "smart_pointers_rc"
version = "0.1.0"
authors = ["Lucas Ambrosi Derrossi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
